[general]
python_version = "3.11"

[server]
headless = true
port = 8501

[client]
showErrorDetails = true

[logger]
level = "info"

[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#000000"
font = "sans serif"

